#name: furniture-store
#
#on:
#  push:
#    branches:
#
#  pull_request:
#    branches:
#
#
#jobs:
#  build-docker:
#    runs-on: ubuntu-latest
#    name: Build and push Docker image
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#        with:
#          fetch-depth: 0
#      - name: Set up JDK 17
#        uses: actions/setup-java@v3
#        with:
#          java-version: '17'
#          distribution: 'temurin'
#          cache: maven
#      - name: Build project
#        run: mvn package
#        working-directory: ./backend
#      - name: Build & push Docker image
#        uses: mr-smithers-excellent/docker-build-push@v5
#        with:
#          image: dangquy1108/furniture-store
#          tags: latest
#          registry: docker.io
#          dockerfile: ./backend/Dockerfile
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
